version: '3.5'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - postgres_v:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_net
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4:6.19
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_v:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres_net
    restart: always
    depends_on:
      - bd

networks:
  postgres_net:

volumes:
    postgres_v:
    pgadmin_v:
